# Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels: {app: swagger-ui}
  template:
    metadata:
      labels: {app: swagger-ui}
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:latest
          ports: [{containerPort: 8080}]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            # Browser will fetch spec from proxy NodePort
            - name: SWAGGER_JSON_URL
              value: http://localhost:32080/openapi.json
            - name: DISPLAY_OPERATION_ID
              value: "true"
            - name: DEEP_LINKING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui-service
spec:
  type: NodePort
  selector: {app: swagger-ui}
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32027 # http://localhost:32027
